### ISSUE TITLE
Routerware ads getting more sophisticated

### ISSUE THREAD

**Issue by JoshTheDerf** [Nateowami/Backloader#11]
Previously, only one IP and ad link were getting injected into requests.

As of yesterday, I'm now getting domains and ips from all over the place, all injecting (working) popup-ads with highly varying id names. I took a look at some of the source code, but it's different for every ad. Most track everything they possibly can get from your browser to uniquely identify you. Awesome.

By this point, it's not even funny. I've got a list of about seven domains to block in BackLoader, but I'm trying to find one master pattern or domain. (Oddly enough, I think it may be the one that I thought didn't do anything ages ago, the one with `backCall({})....`)

To fix/get around this some page inspection may be required. Is that a thing you want? Should I bother adding this to the main repo or just keep it in my fork?

**Comment by Nateowami** [comment]
That's a good question. Have you been able to confirm that it's being done by the router (not the ISP)? For the moment let's just keep them in your branch, since you're the only one using Backloader who has experienced such a router.

That said, I wouldn't be against filters for that in the future, but if they require inspecting the page (and not just blocking or redirecting URLs, then it's probably best to stick them in another extension. Otherwise you have one extension doing essentially two things. You _might_ be able to find an extension that allows you to give it code to be executed on every page, which would be a tad simpler than developing a full-blown extension.

Never mind: seems Chrome has built-in support for user scripts. See http://stackoverflow.com/questions/5258989/manually-adding-a-userscript-to-google-chrome and https://www.chromium.org/developers/design-documents/user-scripts. Not sure if those are helpful or not, but I certainly did not know about this when I created Backloader and JasmineDiff.

**Comment by JoshTheDerf** [comment]
@Nateowami I was pretty sure that it was the router, because both the 4th floor and 8th floor are on the same network, and I never experienced it on the 4th floor (until yesterday.) So yeah, it might be the ISP.

And yeah, user scripts are a thing. :D

**Comment by Nateowami** [comment]
What ISP are you using? If you have two computers there you could launch a server on one (you probably know about `python -m SimpleHTTPServer`) and access pages on the other and see if they are affected. And I assume this only affects HTTP (not HTTPS)? And is observable outside the browser (e.g. with `wget`)?

**Comment by JoshTheDerf** [comment]
@Nateowami It only happens once every few pages or so, at random. I haven't done any considerable testing with it due to lack of time. HTTPS sites are not affected, and it seems that only some HTTP sites are. (StackOverflow being a prime example)
