### ISSUE TITLE
Compatibility with Mozilla's WebExtensions API

### ISSUE THREAD

**Issue by JoshTheDerf** [Nateowami/Backloader#12]
With the new announcement that Mozilla Firefox will be using a near-chrome-compatible extension API, and the enabling of said API in Firefox 42 betas, the opportunity for BackLoader to function in Firefox is now wide open.

Since I happen to have Firefox Developer Edition installed already, I updated it to the latest version and attempted to install BackLoader. It took adding a couple of lines to manifest.json, and enabling unsigned extensions to get it to install. The icon appeared properly, but there are a few things to work through before it will be functional.

Completing this would make this extension compatible with:
- Chrom(e/ium) (Tested)
- Opera (Tested)
- Vivaldi (Snapshots, Tested)
- Firefox 42+ (TODO)
- Most other blink-based browsers, such as Maxathon (Works, but lacks method to install via GUI.)

Todo List:
- [x] Work around missing `chrome.runtime.onInstalled` event, perhaps using a boolean variable in local storage. This kills BackLoader from the get-go.
- [x] ???

I'd like to request permission to create a milestone for this? Maybe for 0.3.0?

**Comment by Nateowami** [comment]
Wow! Hadn't heard about that! I knew Opera used Webkit (or did they switch to Blink?), but didn't realize the extension functionality was built into Webkit/Blink.

I would think Firefox would have something similar to `onInstalled`, but if not, using local storage would be the way to go.

Sure you can make a milestone for this! I would be tempted to call it "Firefox compatibility," but 0.3.0 wouldn't be a bad choice.

Not far from the release of 0.2.0, however, I'd be nice if we didn't have to use useso, because it only works in China. Of course you can just disable Backloader, but it's an extra inconvenience and everyone has to be told to do it (not to mention, if you have a VPN literally kicking on and off every few seconds, it gets pretty bothersome). Most of the popular libraries are on `cdnjs.cloudflare.com/ajax/`. So yeah, this would probably end up in 0.3.0, though it could possibly make it to 0.2.0.

**Comment by JoshTheDerf** [comment]
@Nateowami Sure, we can switch from useso. It's just the only China-based CDN that I know of that maps 1:1. How well does cloudflare map?

I'm not sure the extension functionality is built in. Sure seems like each vendor re-implements at least significant parts of the API, but I may be wrong.

At the moment Firefox has no `onInstalled` listener. The [API](https://wiki.mozilla.org/WebExtensions#List_of_supported_APIs) is still quite incomplete.

EDIT:

> **I'd be nice** if we didn't have to use useso,

Please don't hurt me. :C

**Comment by Nateowami** [comment]
Not sure. It works well with jQuery. Website is https://cdnjs.com/. Perhaps we should use cdnjs when possible, and fall back on useso?

**Comment by JoshTheDerf** [comment]
@Nateowami No idea on how we'd implement that. :/

Currently stopped by an API implementation bug, it crashes when an extension attempts to access a localstorage value that doesn't exist.
I also sorted the folders a bit to make automated distributable building easier.

**Comment by JoshTheDerf** [comment]
Basic working support for Firefox Nightly (10 hours ago had an important bugfix). implemented in my fork. Forgot to separate it into multiple commits. My bad.

Closing this issue in favor of #13 due to compatibility having been attained.
